### ISSUE TITLE
Missing Files Make this Repo Unusable

### ISSUE THREAD

**Issue by Miserlou** [gevaertlab/DAPL#1]
It appears that there are some files which are missing from this repo which make it unusable. 

Most importantly, `utils.py` is absent, so none of the main functions run.

Additionally, it appears that all of the data files are missing as well (`rna_naremoved_logtransformed_normalized.csv`), so it's impossible to verify any of your results. 

These values are also hardcoded, so other input can't be supplied through the command line interface.

It'd be great if you could update this repo to include these missing files so that we can explore your results! Thanks!

**Comment by Miserlou** [comment]
@ogevaert

**Comment by linayqiu** [comment]
Thanks for the comments. Scripts are updated.

**Comment by Miserlou** [comment]
Excellent, thank you!
