### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by Miserlou** [gevaertlab/DAPL#2]
There is no free and open source licensing information attached to this repo, meaning that it can't be used in real systems.

It'd be great if you could [choose and attach a Free and Open Source license](https://help.github.com/articles/licensing-a-repository/) to go along with this project!

Thanks!

**Comment by linayqiu** [comment]
Thanks for bringing up this issue. A license is added to the repo.

**Comment by Miserlou** [comment]
Excellent! Thank you!
